# This workflow will install Python dependencies and generate documentation
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Documentation Generator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Doxygen Action
      # You may pin to the exact commit or the version.
      # uses: mattnotmitt/doxygen-action@cbe72c8e402e8a3faa1f0b247ef90aa6c8e4ce74
      uses: mattnotmitt/doxygen-action@1.9.8
      with:
        # Path to Doxyfile
        doxyfile-path: docs/Doxyfile # default is ./Doxyfile
        # Working directory
        working-directory: . # default is .
        # Generate latex documentation
        enable-latex: true # optional
        # Extra alpine packages for the build environment
        # additional-packages: # optional, default is 
    - name: Move generated site to docs folder
      run: |
        cp -r html/* docs/
        rm docs/Doxyfile
    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: |
          ./latex/*.pdf
          ./docs/
          ./docs
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v4.0.0
      with:
        # Artifact name
        name: github-pages # optional, default is github-pages
        # Path of the directory containing the static assets.
        path: docs/ # default is _site/
        # Duration after which artifact will expire in days.
        retention-days: 1 # optional, default is 1
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action

